### ISSUE TITLE
Terraform study 1st에 오신것을 환영합니다!

### ISSUE THREAD

**Issue by wjrmffldrhrl** [wjrmffldrhrl/Terraform-Study-1st#1]
Terraform 스터디에 관심 가져주시고 방문해주셔서 감사합니다.

혼자서   금방 포기하는 제 모습을 발견했습니다.

여러분들과 함께 스터디를 진행하면서 서로 독려하고 좋은 결과를 만들어내 보려고 합니다.

아직 스터디 경험이 많지 않아서 운영이 익숙하지 않습니다.

많은 의견 주시면 빠르게 반영하고 발전시켜 나가보겠습니다.  

참여를 원하시는 인원은 해당 이슈에 코멘트 남겨주세요

감사합니다.

**Comment by kgw7401** [comment]
참여 희망합니다!

**Comment by yi-eunbin** [comment]
참여 희망합니다

**Comment by heartcored98** [comment]
저도 참여 희망합니다!

**Comment by ssilb4** [comment]
참여 희망합니다

**Comment by wjrmffldrhrl** [comment]
모두 환영합니다 ㅎㅎㅎ
오늘 오후 10시에 구글밋으로 planning 미팅이 있어요
#3 에서 어떤 내용 다룰지 확인하실 수 있어요 
필참은 아니고 앞으로 어떻게 진행할지 맞춰보는 시간 가져보려고 해요~!

**Comment by Gyeong-Hyeon** [comment]
참여 희망합니다. 오늘 10시에 구글밋에서 뵙겠습니다 :)
