### ISSUE TITLE
[Week 2] Getting Started with Terraform, 2022-12-04 21:00

### ISSUE THREAD

**Issue by wjrmffldrhrl** [wjrmffldrhrl/Terraform-Study-1st#16]
# 2주차 Getting Started with Terraform

[구글밋 주소](https://meet.google.com/kqo-ggjy-ztm)

벌써 스터디의 절반이 지나갔어요  

해당 챕터에서는 아래와 같은 내용을 다루고 있어요
- Setting up your AWS account
- Installing Terraform
- Deploying a single server
- Deploying a single web server
- Deploying a configurable web server
- Deploying a cluster of web servers
- Deploying a load balancer
- Cleaning up

비용이 발생하지 않도록 주의하면서 해봐요  

책에 나오는 예시 코드들은 모두 아래 주소에서 확인 가능해요  
- https://github.com/brikis98/terraform-up-and-running-code

**Comment by wjrmffldrhrl** [comment]
Chapter 2부터 aws credential을 사용해야 해요  

기존에 AWS 사용중이라 별도로 관리하고 싶으신 분은 credential directory 생성해서 거기 저장해두세요 [.gitignore](https://github.com/wjrmffldrhrl/Terraform-Study-1st/blob/9a10817f22030ae4e069bc26e7ae613acbb98273/.gitignore)에 반영해서 repo에는 안올라갈거에요

**Comment by wjrmffldrhrl** [comment]
@heartcored98 혹시 구글밋 초대 가능하실까용??

**Comment by heartcored98** [comment]
@wjrmffldrhrl 엇 방금 초대드릴려고 했는데, 벌써 초대를 주셨군요. ㅎㅎ 오늘은 그럼 승현님 초대 링크로 들어가겠습니다~ 회사 계정이시면 아마 유료 계정일겁니다!

**Comment by 0805004949** [comment]
안녕하세요! 죄송하지만 아직 집에 가는 중이라  30분정도 지각예정입니다 ㅠ_ㅠ
 잠시후에 뵙겠습니다

**Comment by wjrmffldrhrl** [comment]
yes 없이 terraform apply 수행하기  
`terroform apply --auto-approve`

**Comment by wjrmffldrhrl** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group  

terraform aws security group에서 self parameter란?

**Comment by Gyeong-Hyeon** [comment]
> https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group
> 
> terraform aws security group에서 self parameter란?

관련 AWS [공식문서](https://docs.aws.amazon.com/ko_kr/glue/latest/dg/start-development-endpoint.html)입니다 (Security Group 자기참조) - 5번 참고해주시면 됩니다.

코드는 다음과 같습니다.

```
  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    self        = true
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    self        = true
  }
```

**Comment by ssilb4** [comment]
[security_groups](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#security_groups) 에 설정할 security group들을 넣을 수 있는데, 자기 자신의 security group은 아직 생성 전이라 인자로 따로 받는 것처럼 생각되네요.
