### ISSUE TITLE
[Week 0] Planning (optional), 2022-11-20 22:00

### ISSUE THREAD

**Issue by wjrmffldrhrl** [wjrmffldrhrl/Terraform-Study-1st#3]
# 0주차 Planning
[구글 밋 참여 링크](https://meet.google.com/wtd-qyrh-yve)
# Agenda
## 스터디 모임 시간

**매주 일요일 오후 10시**  
- 평일은 불시에 야근이 생길 수 있고 일상 생활에서 피로가 쌓일 수 있어서 피했어요  
- 집중해서 책을 읽을 수 있는 주말을 스터디 사이에 넣는게 좋다고 생각했어요  
- 모두가 집에 있을 수 있는 시간인 일요일 오후 10시로 정했어요

## 내용 정리

파일 구조는 두 가지 방법을 생각했어요
### 1. 참여자 별로 디렉터리 생성
```
├─Terraform-Study-1st
│  ├─wjrmffldrhrl
│  │  ├─chapter_1.md
│  ├─bob_jo
│  │  ├─chapter_1.md
```

### 2. Chapter 별로 디렉터리 생성
```
├─Terraform-Study-1st
│  ├─chapter_1
│  │  ├─wjrmffldrhrl
│  │  │  ├─README.md
│  │  │  ├─example.tf
│  │  ├─bob_jo
│  │  │  ├─README.md
│  ├─chapter_2
``` 
root dir에서 봤을 때 2번이 더 깔끔할 것 같아요  

파일 공유는 모두 PR로 받아서 적용하려고 해요  
- 참여 하시는 분들 모두 권한 드리는것 보다 한 명이 전체적으로 관리하는게 더 좋을 것 같아요

## 장소

zoom이나 google meet 사용하는게 좋을 것 같아요  
- discord는 로그인이 잘 안될때가 있더라구요  

그런데 둘 모두 시간 제한이 있어서 구성원분들 중 유료 계정 있으신분 없으면 제가 결제해서 사용하려고 해요
## 진행 방법

[README.md](https://github.com/wjrmffldrhrl/Terraform-Study-1st#eyes-%EC%A7%84%ED%96%89-%EB%B0%A9%EB%B2%95tbd) 참고해주세요  
다양한 의견 받아요~!
## ETC
- 책 구매
- 불참
- 지각

**Comment by wjrmffldrhrl** [comment]
### 스터디 모임 시간
일요일 오후 10시 -> 오후 9시

**Comment by wjrmffldrhrl** [comment]
### 내용 정리
2번 옵션 기준으로 해당 챕터 내용 정리해서 모두가 퀄리티 올려볼 수 있도록  
- 각자 정리한 내용들도 다같이 확인할 수 있도록

**Comment by Gyeong-Hyeon** [comment]
kyunghyun7843@gmail.com 입니다

**Comment by JamesHeo** [comment]
heojstats@gmail.com 입니다.

**Comment by teno4944** [comment]
qqllio4944@gmail.com 입니다

**Comment by heartcored98** [comment]
위에 3분 캘린더 초대드렸습니다! 다른 참석자 분들도 이메일 주소 댓글로 남겨주세요~

**Comment by wjrmffldrhrl** [comment]
wjrmffldrhrl@gmail.com 입니다~!

**Comment by ssilb4** [comment]
ssilb4@gmail.com 입니다

**Comment by ssilb4** [comment]
아까 3판이 새로 나왔다는 건 원서 기준인 건가요?
이게 맞다면 승현님이 3판을 구매하셨다고 하신 것 같은데 원서로 하시는 건가요? (이건 개인적인 궁금증이요!)

**Comment by wjrmffldrhrl** [comment]
@ssilb4 
네 맞아요  2022년 9월에 원서 3판이 새로 나왔어요  
회사에서 Oreilly 구독중이라 원서 읽어보려고 합니당

아직 영어 잘 못하지만 😢  이번 기회에 공부해보려고요

**Comment by wjrmffldrhrl** [comment]
<img width="931" alt="Screenshot 2022-11-20 at 10 47 48 PM" src="https://user-images.githubusercontent.com/49122299/202905681-c2527dff-3911-48d7-acc3-dc40761e8cb9.png">
그리고 지금 봤는데 Oreilly 10일 free trial이 있네요  

책 도착전까지 필요하신분 사용하시면 될 것 같아요  

그래도 혹시나 1챕터 PDF 필요하신분들은 제 이메일로 말씀해주세요~!  
- wjrmffldrhrl@gmail.com

**Comment by ssilb4** [comment]
아하 구독 서비스가 있군요..
원서에 관심있는데 이 책은 비싸네요 ㅎ

**Comment by wjrmffldrhrl** [comment]
번역본 쿠팡에서 판매하더라구요  
https://www.coupang.com/vp/products/5455660041?itemId=8337781901&vendorItemId=76306634686&q=%ED%85%8C%EB%9D%BC%ED%8F%BC&itemsCount=36&searchId=8c884f8cffbd4e30aa37bc29c2e9d86d&rank=1&isAddedCart=  

저도 읽다가 속도 안나오면 번역본으로 도망갈 예정입니다 😅

**Comment by JionisGenius** [comment]
rnrmfwldwlddl@gmail.com
입니다!

**Comment by heartcored98** [comment]
추가로 4분 캘린더 초대 완료했습니다!

**Comment by 0805004949** [comment]
안녕하세요! crispylegs1921@gmail.com 
스터디 지금 신청 가능할까요?

**Comment by wjrmffldrhrl** [comment]
@0805004949 안녕하세요~! 

1주차 스터디 모임까지 3일정도 남아서 괜찮을 것 같아요  

진행하시는데 어려움 있으면 편하게 말씀해주시고 성함도 같이 추가해주시면 감사드리겠습니다 😄

**Comment by 0805004949** [comment]
책 없으신 분들은
https://libgen.is/book/index.php?md5=1C65EE411EF3B35D43DE2E948A0D1226
여기서  epub으로 2nd edition 받으실 수 있고
epub->pdf https://www.zamzar.com/convert/epub-to-pdf/요런거 이용해서 pdf로 뽑으셔도 될 것 같아요!
한편 @wjrmffldrhrl 아직 구글 캘린더에 초대 메일을 받지 못했는데 혹시 확인해주실 수 있나요? 😁
