### ISSUE TITLE
회사에서 테라폼 협업 어떻게 하시나요?

### ISSUE THREAD

**Issue by JamesHeo** [wjrmffldrhrl/Terraform-Study-1st#31]
인프라 변경하고자 하는 부분을 업데이트하여 깃헙에 업로드하면 테라폼이 이를 추적하여 적용시키나요?
아니면 개인 머신에 'terraform apply' 커맨트 실행하여 변경사항 적용 후 version control 목적으로 깃헙에 변경된 코드를 업로드 하나요?

**Comment by wjrmffldrhrl** [comment]
저희는 [Atlantis](https://www.runatlantis.io/)를 사용하고 있어요  

변경사항에 대해서 GitHub PR에서 반영할 수 있도록 도움 주는 도구에요

**Comment by JamesHeo** [comment]
오 그렇군요..! 좋은 정보 감사합니다!! PR 과정에서 팀원들 같이 리뷰를 할 수 있겠군요!

**Comment by wjrmffldrhrl** [comment]
넵넵 그리고 같은 리소스에 대해서 2개 이상 PR이 열리는걸 막아주는 역할도 해주더라구요

**Comment by JamesHeo** [comment]
중복 PR도 방지해주는 군요.. 제가 저희 팀이나 회사측면으로 도입해보도록 해보겠습니다 ㅎㅎ
