### ISSUE TITLE
[Week 3] How to Manage Terraform State, 2022-12-11 21:00

### ISSUE THREAD

**Issue by wjrmffldrhrl** [wjrmffldrhrl/Terraform-Study-1st#35]
# 3주차 How to Manage Terraform State

[구글밋 주소](https://meet.google.com/kqo-ggjy-ztm)  

해당 챕터에서는 아래와 같은 내용을 다루고 있어요
- What is Terraform state?
- Shared storage for state files 
- Limitations with Terraform’s backends 
- State file isolation
  - Isolation via workspaces
  - Isolation via file layout
- The terraform_remote_state data source

이번 스터디에서 중요한 부분 중 하나라고 생각해요

**Comment by Gyeong-Hyeon** [comment]
오늘 개인적인 일정으로 스터디 참석이 힘들 것 같아요 ㅜ.ㅜ 다음 주에 뵙겠습니다

**Comment by wjrmffldrhrl** [comment]
@Gyeong-Hyeon 넵넵 ㅎㅎㅎ 내용 정리만 천천히 챙겨주세요~!

**Comment by kgw7401** [comment]
오늘 조금 늦게 들어갈 거 같네요 ㅠㅠ 최대한 빨리 들어가겠습니다

**Comment by wjrmffldrhrl** [comment]
@kgw7401 넵넵 도착하시면 들어와주세용~!

**Comment by 0805004949** [comment]
- 테라폼에서 정말로 테라폼 상태파일을 격리 시켜줄까?
https://github.com/wjrmffldrhrl/Terraform-Study-1st/tree/main/personal/kevin/chapter_3
@JamesHeo

**Comment by 0805004949** [comment]
-  책 예제에서는 aws s3 + dynamo db로 테라폼 상태파일 관리(dynamo db는 locking 때문에)를 했는데  gcp gcs에서는 네이티브로 locking을 지원하고 있었군요 
 https://stackoverflow.com/questions/53413639/what-is-the-mechanism-of-terraform-state-locking-when-using-google-cloud-platfor

**Comment by wjrmffldrhrl** [comment]
> 책 예제에서는 aws s3 + dynamo db로 테라폼 상태파일 관리(dynamo db는 locking 때문에)를 했는데 gcp gcs에서는 네이티브로 locking을 지원하고 있었군요  

이부분은 GCP가 확실히 잘 해주네요 ㅋㅋㅋ
