### ISSUE TITLE
[Week 1] Why Terraform, 2022-11-27 21:00

### ISSUE THREAD

**Issue by wjrmffldrhrl** [wjrmffldrhrl/Terraform-Study-1st#4]
# 1주차 Why Terraform  
[구글 밋 참여](https://meet.google.com/dpa-wtca-nao)

첫 스터디가 시작됐어요  
해당 챕터에서는 아래와 같은 내용들을 다루고 있어요
- What is DevOps?
- What is infrastructure as code?
- What are the benefits of infrastructure as code?
- How does Terraform work?
- How does Terraform compare to other infrastructure-as-code tools?

**Comment by wjrmffldrhrl** [comment]
https://techblog.woowahan.com/2646/

**Comment by Gyeong-Hyeon** [comment]
저 비행기가 연착돼서 회의 15분 정도 늦게 도착할 것 같습니다 :( 이따 봴게요

**Comment by heartcored98** [comment]
오늘 저녁에 가족 모임이 잡히는 바람에.. 첫 차수부터 불참을 하게 되었네요. 건우님께 구글 밋 제어권을 드렸습니다! 아쉽지만 다음 주에 뵐게요.

**Comment by wjrmffldrhrl** [comment]
은빈님 어디계시나요~

**Comment by wjrmffldrhrl** [comment]
배포전략
https://onlywis.tistory.com/10

**Comment by 0805004949** [comment]
마이크로서비스 업앤러닝
https://www.oreilly.com/library/view/microservices-up-and/9781492075448/

**Comment by wjrmffldrhrl** [comment]
첫 스터디 고생 많으셨어요 ㅎㅎㅎ  

#15 에 일단 제가 정리한 내용 추가했어요  
수정사항이나 추가할 내용 comment로 남겨주세요~!  

배포전략과 master, agent 보안 또는 저희 얘기 나눈것들도 추가해주셔도 좋아요  

저도 계속 보면서 수정해볼게요 🙇

**Comment by 0805004949** [comment]
https://www.serverless.com/ 
이거는 현재 저희 회사에서 사용중인  IaC툴  서버리스입니다..
책에 나온대로  `configuration management tools`인지 `provisioning tools`인지는 조금 더 문서를 읽고 확인해봐야하겠지만
공유차 링크 남겨봅니다!! (추후 내용 간단히 정리해서 추가하겠습니다)
