### ISSUE TITLE
[Week 4] How to Create Reusable Infrastructure with Terraform Modules, 2022-12-18 21:00

### ISSUE THREAD

**Issue by wjrmffldrhrl** [wjrmffldrhrl/Terraform-Study-1st#42]
# 4주차 How to Create Reusable Infrastructure with Terraform Modules

[구글밋 주소](https://meet.google.com/kqo-ggjy-ztm)  

해당 챕터에서는 아래와 같은 내용을 다루고 있어요

- Module basics 
- Module inputs 
- Module locals 
- Module outputs 
- Module gotchas 
- Module versioning

마지막 스터디가 다가왔네요  

오늘은 끝나고 향후 계획에 대해서도 이야기 나눠볼게요

**Comment by ssilb4** [comment]
제가 지방에 왔다가 오늘 올라가느라 늦거나 불참할 수도 있을 것 같습니다.

**Comment by wjrmffldrhrl** [comment]
@ssilb4 넵넵 도착하시면 편하게 접속해주세요~

**Comment by 0805004949** [comment]
10분에 접속하겠습니다 죄송합니다 !! @wjrmffldrhrl

**Comment by kgw7401** [comment]
지금 스터디 진행하고 있는건가요??

**Comment by wjrmffldrhrl** [comment]
@0805004949 넵넵 천천히 접속해주세요~!

**Comment by wjrmffldrhrl** [comment]
@kgw7401 넵 시작했습니다. 참여 안되시나요?

**Comment by kgw7401** [comment]
@wjrmffldrhrl 네 초대요청을 했는데 허용이 안되고 있습니다!

**Comment by kgw7401** [comment]
@wjrmffldrhrl 혹시 따로 요청이 안가고 있나요?

**Comment by wjrmffldrhrl** [comment]
네네 위 링크 접속 안되실까요?

**Comment by wjrmffldrhrl** [comment]
화상 회의에 참여하려면 다음 링크를 클릭하세요. https://meet.google.com/kqo-ggjy-ztm
휴대전화로 참여하려면 +1 401-753-9599번호로 전화를 걸고 다음 PIN을 입력하세요. 891 113 908#
전화번호를 더 보려면 다음 링크를 클릭하세요. https://tel.meet/kqo-ggjy-ztm?hs=5

**Comment by kgw7401** [comment]
@wjrmffldrhrl 저 링크로 들어갔는데 그래도 요청이 안갈까요? 계속 이 화면만 뜨네요
<img width="1258" alt="스크린샷 2022-12-18 오후 9 09 56" src="https://user-images.githubusercontent.com/78521993/208297599-b101a956-fcc0-442d-a748-75d6430c8136.png">
